# Model configuration
model:
  name: "meta-llama/Llama-3.2-3B-Instruct"
  new_model_name: "llama-3-ft"

# Dataset configuration
dataset:
  name: "databricks/databricks-dolly-15k"
  text_field: "text"
  seed: 42

# LoRA parameters
lora:
  r: 64
  alpha: 16
  dropout: 0.1

# Quantization parameters
quantization:
  use_4bit: true
  compute_dtype: "float16"
  quant_type: "nf4"
  use_nested_quant: false

# Training parameters
training:
  output_dir: "./results"
  num_train_epochs: 1
  fp16: false
  bf16: false
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 1
  gradient_checkpointing: true
  max_grad_norm: 0.3
  learning_rate: 2.0e-4
  weight_decay: 0.001
  optim: "paged_adamw_32bit"
  lr_scheduler_type: "cosine"
  max_steps: -1
  warmup_ratio: 0.03
  group_by_length: true
  save_steps: 0
  logging_steps: 25
  max_seq_length: null
  packing: false 